# Generated by Django 5.0.8 on 2025-01-20 07:10

import django.db.models.deletion
import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HNIdeas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False, verbose_name="创建时间")),
                ("modified", models.DateTimeField(editable=False, verbose_name="修改时间")),
                ("url", models.CharField(max_length=255)),
                ("story_id", models.CharField(max_length=64)),
                ("comment_id", models.CharField(max_length=64)),
                ("summary", models.TextField()),
                ("origin_text", knowledge.models.MediumTextField(default="")),
            ],
            options={
                "verbose_name": "ideas",
                "verbose_name_plural": "ideas",
            },
        ),
        migrations.CreateModel(
            name="HtmlPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False, verbose_name="创建时间")),
                ("modified", models.DateTimeField(editable=False, verbose_name="修改时间")),
                ("html", knowledge.models.MediumTextField()),
                ("text", knowledge.models.MediumTextField(default="")),
                ("summary", models.TextField(default="")),
                ("url", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT_PROCESS", "等待处理"),
                            ("PROCESSING", "处理中"),
                            ("FINISH", "处理完成"),
                        ],
                        default="WAIT_PROCESS",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "网页知识点",
                "verbose_name_plural": "网页知识点",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "html_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="knowledge.htmlpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.CreateModel(
            name="Vector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector_id", models.UUIDField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "html_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vectors",
                        to="knowledge.htmlpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "向量存储",
                "verbose_name_plural": "向量存储",
            },
        ),
    ]
