# Generated by Django 5.1 on 2024-08-24 06:25

import knowledge.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpage',
            name='html',
            field=knowledge.models.MediumTextField(),
        ),
    ]
