# Generated by Django 5.1 on 2024-08-24 06:53

import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_htmlpage_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='htmlpage',
            name='text',
            field=knowledge.models.MediumTextField(default=''),
        ),
    ]
