# Generated by Django 5.0.8 on 2025-02-17 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_conversation_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteCrawlRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("article_list_selector", models.CharField(max_length=255)),
                ("article_link_selector", models.CharField(max_length=255)),
                ("article_title_selector", models.CharField(max_length=255)),
                ("article_content_selector", models.CharField(max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "用户"), ("assistant", "助手")],
                max_length=20,
                verbose_name="发送者",
            ),
        ),
    ]
