# Generated by Django 5.0.8 on 2024-08-25 08:26

import knowledge.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_hnideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hnideas',
            name='origin_text',
            field=knowledge.models.MediumTextField(default=''),
        ),
    ]
