# Generated by Django 5.0.8 on 2024-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0003_goodsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='cclTrending',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goods',
            name='pcIndex',
            field=models.CharField(default='', max_length=255),
        ),
    ]
