# Generated by Django 5.1 on 2024-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('modified', models.DateTimeField(editable=False, verbose_name='修改时间')),
                ('uid', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
