# Generated by Django 5.1 on 2024-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrss',
            options={'verbose_name': 'rss', 'verbose_name_plural': 'rss'},
        ),
        migrations.AlterField(
            model_name='userrss',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrss',
            unique_together={('uid', 'title'), ('uid', 'url')},
        ),
    ]
