# Generated by Django 5.1 on 2024-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userrss_options_alter_userrss_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrss',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
