# Generated by Django 5.1 on 2024-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userrss_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('modified', models.DateTimeField(editable=False, verbose_name='修改时间')),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entry',
            },
        ),
    ]
