# Generated by Django 5.1 on 2024-08-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rssentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrss',
            name='source_type',
            field=models.CharField(default='feeds', max_length=255),
        ),
    ]
