# Generated by Django 5.1 on 2024-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('modified', models.DateTimeField(editable=False, verbose_name='修改时间')),
                ('uid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ai任务',
                'verbose_name_plural': 'ai任务',
            },
        ),
        migrations.CreateModel(
            name='SummaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('modified', models.DateTimeField(editable=False, verbose_name='修改时间')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='waiting', max_length=255)),
                ('result', models.TextField(default='')),
            ],
            options={
                'verbose_name': '新闻总结',
                'verbose_name_plural': '新闻总结',
            },
        ),
    ]
