# Generated by Django 5.1 on 2024-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytask',
            name='type',
            field=models.CharField(default='summarize', max_length=255),
        ),
        migrations.AlterField(
            model_name='summarytask',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
