# Generated by Django 5.1 on 2024-08-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitask', '0003_alter_aitask_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytask',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
